version: 2
general:
  branches:
    only:
      - master
      - publishment
      - release
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: ~/project/.travis/tests.sh
      - run: ~/project/.circleci/deploy.sh
