FROM jamesmcclain/crossbuild:0
LABEL maintainer="James McClain <james.mcclain@gmail.com>"

RUN apt-get update -q && \
    apt-get install build-essential libgdal-dev openjdk-8-jdk -y -q && \
    apt-get autoremove && \
    apt-get autoclean && \
    apt-get clean

# Test data
RUN wget 'https://download.osgeo.org/geotiff/samples/usgs/c41078a1.tif' -k -O /tmp/c41078a1.tif

# Boost
RUN wget 'https://dl.bintray.com/boostorg/release/1.69.0/source/boost_1_69_0.tar.bz2' -O /tmp/boost.tar.bz2 && \
  mkdir -p /usr/local/include && \
  cd /usr/local/include && \
  tar axvf /tmp/boost.tar.bz2 && \
  rm /tmp/boost.tar.bz2

# Macintosh
RUN mkdir -p /macintosh && \
    cd /macintosh && \
    wget "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08/OpenJDK8U-jdk_x64_mac_hotspot_8u202b08.tar.gz" && \
    tar axvf OpenJDK8U-jdk_x64_mac_hotspot_8u202b08.tar.gz && \
    rm -f OpenJDK8U-jdk_x64_mac_hotspot_8u202b08.tar.gz && \
    wget "https://homebrew.bintray.com/bottles/gdal-2.4.0_1.sierra.bottle.tar.gz" && \
    tar axvf gdal-2.4.0_1.sierra.bottle.tar.gz && \
    rm -f gdal-2.4.0_1.sierra.bottle.tar.gz

# Windows
RUN mkdir -p /windows && \
    cd /windows && \
    wget "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08/OpenJDK8U-jdk_x64_windows_hotspot_8u202b08.zip" && \
    unzip OpenJDK8U-jdk_x64_windows_hotspot_8u202b08.zip && \
    rm -r OpenJDK8U-jdk_x64_windows_hotspot_8u202b08.zip && \
    mkdir -p /windows/gdal && \
    cd /windows/gdal && \
    wget "http://download.gisinternals.com/sdk/downloads/release-1900-x64-gdal-2-4-0-mapserver-7-2-2-libs.zip" && \
    unzip release-1900-x64-gdal-2-4-0-mapserver-7-2-2-libs.zip && \
    rm -f release-1900-x64-gdal-2-4-0-mapserver-7-2-2-libs.zip

# docker build -f Dockerfile.environment -t jamesmcclain/gdal-build-environment:3 .
