#!/bin/bash

set -e

docker run -it --rm \
      -v $(pwd):/workdir \
      -e OSXCROSS_NO_INCLUDE_PATH_WARNINGS=1 \
      -e CROSS_TRIPLE="x86_64-apple-darwin" \
      -e OS=darwin -e SO=dylib \
      -e CC=cc -e CXX=c++ \
      -e CFLAGS="-Wall -Werror -O0 -ggdb3" \
      -e JAVA_HOME="/macintosh/jdk8u202-b08/Contents/Home" \
      -e GDALCFLAGS="-I/macintosh/gdal/2.4.2_3/include" \
      -e CXXFLAGS="-I/usr/osxcross/SDK/MacOSX10.10.sdk/usr/include/c++/v1"  \
      -e BOOST_ROOT="/usr/local/include/boost_1_69_0" \
      -e LDFLAGS="-mmacosx-version-min=10.9 -L/macintosh/gdal/2.4.2_3/lib -lgdal -lstdc++ -lpthread" \
      jamesmcclain/gdal-build-environment:4 make -j4 -C src libgdalwarp_bindings.dylib || exit -1

docker run -it --rm \
      -v $(pwd):/workdir \
      -e CROSS_TRIPLE=x86_64-w64-mingw32 \
      -e OS=win32 \
      -e CFLAGS="-Wall -Werror -Os -g" \
      -e JAVA_HOME="/windows/jdk8u202-b08" \
      -e GDALCFLAGS="-I/usr/local/include" \
      -e BOOST_ROOT="/usr/local/include/boost_1_69_0" \
      -e LDFLAGS="-L/windows/gdal/lib -lgdal_i -lstdc++ -lpthread -lws2_32" \
      jamesmcclain/gdal-build-environment:4 make -j4 -C src gdalwarp_bindings.dll || exit -1

cp src/libgdalwarp_bindings.dylib src/main/java/resources/ || exit -1
cp src/gdalwarp_bindings.dll src/main/java/resources/ || exit -1